services:
  app:
    build: .
    ports:
      - 3000:3000
    mem_limit: 2g
    networks:
      - tech-challenge

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/opt/postgres/dbdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - tech-challenge

networks:
  tech-challenge:
