services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    mem_limit: 2g
    networks:
      - tech-challenge

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - tech-challenge

networks:
  tech-challenge:
