services:
  app:
    build: .
    ports:
      - 3000:3000
    mem_limit: 2g
    networks:
      - tech-challenge

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/opt/postgres/dbdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - tech-challenge

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.docker/keycloak/data/import:/opt/keycloak/data/import
      - ./keycloak/theme:/opt/keycloak/providers
      - ./keycloak/config:/opt/keycloak/conf
    ports:
      - 8080:8080
    networks:
      - tech-challenge
    depends_on:
      - db

networks:
  tech-challenge:
