export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const CUSTOMER_USECASE = Symbol('CUSTOMER_USECASE');

export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_USECASE = Symbol('PRODUCT_USECASE');

export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const CATEGORY_USECASE = Symbol('CATEGORY_USECASE');
