apiVersion: v1
kind: Service
metadata:
  name: svc-tech-challenge-api
  labels:
    app: svc-tech-challenge-api
spec:
  selector:
    app: tech-challenge-api-deployment
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
