apiVersion: v1
kind: Service
metadata:
  name: svc-tech-challenge-api
  labels:
    app: svc-tech-challenge-api
spec:
  selector:
    app: tech-challenge-api-deployment
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
